"""Build comprehensive Indian legal database — IPC sections, precedents, SC judgments."""

import json
import sys
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
LEGAL_DB = BASE_DIR / "data" / "legal_database"


IPC_SECTIONS = [
    {"section": "IPC 34", "title": "Acts done by several persons in furtherance of common intention", "description": "When a criminal act is done by several persons in furtherance of the common intention of all, each of such persons is liable for that act in the same manner as if it were done by him alone.", "punishment": "Same as the principal offence", "bailable": None, "cognizable": None, "keywords": ["common intention", "joint liability", "group crime", "abetment"]},
    {"section": "IPC 120B", "title": "Punishment of criminal conspiracy", "description": "Whoever is a party to a criminal conspiracy to commit an offence punishable with death, imprisonment for life or rigorous imprisonment for a term of two years or upwards, shall be punished in the same manner as if he had abetted such offence.", "punishment": "Same as abetment of the offence conspired", "bailable": False, "cognizable": True, "keywords": ["conspiracy", "criminal conspiracy", "gang", "organized crime", "planning"]},
    {"section": "IPC 149", "title": "Every member of unlawful assembly guilty of offence committed in prosecution of common object", "description": "If an offence is committed by any member of an unlawful assembly in prosecution of the common object of that assembly, every person who at the time of the committing of that offence, is a member of the same assembly, is guilty of that offence.", "punishment": "Same as the principal offence", "bailable": None, "cognizable": None, "keywords": ["unlawful assembly", "mob", "riot", "common object"]},
    {"section": "IPC 302", "title": "Punishment for murder", "description": "Whoever commits murder shall be punished with death, or imprisonment for life, and shall also be liable to fine. Murder is defined under Section 300 as culpable homicide amounting to murder when done with intention to cause death or bodily injury sufficient to cause death.", "punishment": "Death or imprisonment for life + fine", "bailable": False, "cognizable": True, "keywords": ["murder", "homicide", "killing", "death", "culpable homicide"]},
    {"section": "IPC 304", "title": "Punishment for culpable homicide not amounting to murder", "description": "Whoever commits culpable homicide not amounting to murder shall be punished with imprisonment for life, or imprisonment for either description for a term which may extend to ten years, and shall also be liable to fine.", "punishment": "Life imprisonment or up to 10 years + fine", "bailable": False, "cognizable": True, "keywords": ["culpable homicide", "manslaughter", "accidental death", "negligent killing"]},
    {"section": "IPC 304A", "title": "Causing death by negligence", "description": "Whoever causes the death of any person by doing any rash or negligent act not amounting to culpable homicide, shall be punished with imprisonment for a term which may extend to two years, or with fine, or with both.", "punishment": "Up to 2 years imprisonment or fine or both", "bailable": True, "cognizable": True, "keywords": ["negligence", "rash act", "accident", "death by negligence", "medical negligence"]},
    {"section": "IPC 307", "title": "Attempt to murder", "description": "Whoever does any act with such intention or knowledge, and under such circumstances that, if he by that act caused death, he would be guilty of murder, shall be punished with imprisonment for a term which may extend to ten years, and shall also be liable to fine.", "punishment": "Up to 10 years + fine; life imprisonment if hurt caused", "bailable": False, "cognizable": True, "keywords": ["attempt to murder", "attempted murder", "try to kill", "assault with intent to kill"]},
    {"section": "IPC 323", "title": "Punishment for voluntarily causing hurt", "description": "Whoever, except in the case provided for by section 334, voluntarily causes hurt, shall be punished with imprisonment for a term which may extend to one year, or with fine which may extend to one thousand rupees, or with both.", "punishment": "Up to 1 year or fine up to Rs. 1000 or both", "bailable": True, "cognizable": False, "keywords": ["hurt", "assault", "beating", "injury", "simple hurt"]},
    {"section": "IPC 324", "title": "Voluntarily causing hurt by dangerous weapons or means", "description": "Whoever, except in the case provided for by section 334, voluntarily causes hurt by means of any instrument for shooting, stabbing or cutting, or any instrument which, used as weapon of offence, is likely to cause death.", "punishment": "Up to 3 years or fine or both", "bailable": False, "cognizable": True, "keywords": ["hurt by weapon", "stabbing", "cutting", "grievous hurt", "weapon assault"]},
    {"section": "IPC 325", "title": "Punishment for voluntarily causing grievous hurt", "description": "Whoever voluntarily causes grievous hurt, shall be punished with imprisonment for a term which may extend to seven years, and shall also be liable to fine.", "punishment": "Up to 7 years + fine", "bailable": False, "cognizable": True, "keywords": ["grievous hurt", "serious injury", "permanent disability", "grievous bodily harm"]},
    {"section": "IPC 354", "title": "Assault or criminal force to woman with intent to outrage her modesty", "description": "Whoever assaults or uses criminal force to any woman, intending to outrage or knowing it to be likely that he will thereby outrage her modesty, shall be punished with imprisonment for a term which shall not be less than one year but which may extend to five years, and shall also be liable to fine.", "punishment": "1 to 5 years + fine", "bailable": False, "cognizable": True, "keywords": ["modesty", "outrage modesty", "sexual harassment", "molestation", "woman assault"]},
    {"section": "IPC 354A", "title": "Sexual harassment and punishment for sexual harassment", "description": "A man committing physical contact and advances involving unwelcome and explicit sexual overtures; or a demand or request for sexual favours; or showing pornography against the will of a woman; or making sexually coloured remarks shall be guilty of sexual harassment.", "punishment": "Up to 3 years or fine or both", "bailable": False, "cognizable": True, "keywords": ["sexual harassment", "workplace harassment", "unwanted advances", "POSH act"]},
    {"section": "IPC 376", "title": "Punishment for rape", "description": "Whoever commits rape shall be punished with rigorous imprisonment for a term which shall not be less than ten years but which may extend to imprisonment for life and shall also be liable to fine. In cases of aggravated rape, the punishment shall not be less than twenty years.", "punishment": "Minimum 10 years RI to life imprisonment + fine", "bailable": False, "cognizable": True, "keywords": ["rape", "sexual assault", "POCSO", "gang rape", "aggravated sexual assault"]},
    {"section": "IPC 379", "title": "Punishment for theft", "description": "Whoever commits theft shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both.", "punishment": "Up to 3 years or fine or both", "bailable": True, "cognizable": True, "keywords": ["theft", "stealing", "larceny", "pickpocket", "shoplifting"]},
    {"section": "IPC 380", "title": "Theft in dwelling house etc.", "description": "Whoever commits theft in any building, tent or vessel, which building, tent or vessel is used as a human dwelling, or used for the custody of property, shall be punished with imprisonment for a term which may extend to seven years, and shall also be liable to fine.", "punishment": "Up to 7 years + fine", "bailable": False, "cognizable": True, "keywords": ["house theft", "burglary", "dwelling theft", "home robbery", "break-in"]},
    {"section": "IPC 392", "title": "Punishment for robbery", "description": "Whoever commits robbery shall be punished with rigorous imprisonment for a term which may extend to ten years, and shall also be liable to fine; and, if the robbery be committed on the highway between sunset and sunrise, the imprisonment may be extended to fourteen years.", "punishment": "Up to 10 years RI + fine; 14 years if on highway after sunset", "bailable": False, "cognizable": True, "keywords": ["robbery", "snatching", "mugging", "chain snatching", "violent theft"]},
    {"section": "IPC 395", "title": "Punishment for dacoity", "description": "Whoever commits dacoity shall be punished with imprisonment for life, or with rigorous imprisonment for a term which may extend to ten years, and shall also be liable to fine.", "punishment": "Life imprisonment or up to 10 years RI + fine", "bailable": False, "cognizable": True, "keywords": ["dacoity", "gang robbery", "armed robbery", "organized robbery", "five or more persons"]},
    {"section": "IPC 406", "title": "Punishment for criminal breach of trust", "description": "Whoever commits criminal breach of trust shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both.", "punishment": "Up to 3 years or fine or both", "bailable": True, "cognizable": True, "keywords": ["breach of trust", "misappropriation", "entrustment", "fiduciary", "embezzlement"]},
    {"section": "IPC 420", "title": "Cheating and dishonestly inducing delivery of property", "description": "Whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any person, or to make, alter or destroy the whole or any part of a valuable security, or anything which is signed or sealed, and which is capable of being converted into a valuable security, shall be punished with imprisonment for a term which may extend to seven years, and shall also be liable to fine.", "punishment": "Up to 7 years + fine", "bailable": False, "cognizable": True, "keywords": ["cheating", "fraud", "deception", "dishonest inducement", "property fraud", "scam", "misrepresentation"]},
    {"section": "IPC 467", "title": "Forgery of valuable security, will, etc.", "description": "Whoever forges a document which purports to be a valuable security or a will, or an authority to adopt a son, or which purports to give authority to any person to make or transfer any valuable security, or to receive the principal, interest or dividends thereon.", "punishment": "Up to 10 years + fine", "bailable": False, "cognizable": True, "keywords": ["forgery", "fake document", "counterfeit", "forged security", "document fraud"]},
    {"section": "IPC 468", "title": "Forgery for purpose of cheating", "description": "Whoever commits forgery, intending that the document forged shall be used for the purpose of cheating, shall be punished with imprisonment for a term which may extend to seven years, and shall also be liable to fine.", "punishment": "Up to 7 years + fine", "bailable": False, "cognizable": True, "keywords": ["forgery", "fake certificate", "forged document", "cheating by forgery"]},
    {"section": "IPC 471", "title": "Using as genuine a forged document or electronic record", "description": "Whoever fraudulently or dishonestly uses as genuine any document or electronic record which he knows or has reason to believe to be a forged document or electronic record, shall be punished in the same manner as if he had forged such document or electronic record.", "punishment": "Same as for forgery of the document used", "bailable": False, "cognizable": True, "keywords": ["using forged document", "fake certificate use", "forged instrument", "document misuse"]},
    {"section": "IPC 498A", "title": "Husband or relative of husband of a woman subjecting her to cruelty", "description": "Whoever, being the husband or the relative of the husband of a woman, subjects such woman to cruelty shall be punished with imprisonment for a term which may extend to three years and shall also be liable to fine.", "punishment": "Up to 3 years + fine", "bailable": False, "cognizable": True, "keywords": ["domestic violence", "cruelty by husband", "dowry harassment", "matrimonial cruelty", "dowry demand"]},
    {"section": "IPC 304B", "title": "Dowry death", "description": "Where the death of a woman is caused by any burns or bodily injury or occurs under suspicious circumstances within seven years of marriage, and it is shown that soon before her death she was subjected to cruelty or harassment by her husband or any relative of her husband for, or in connection with, any demand for dowry.", "punishment": "Minimum 7 years, maximum life imprisonment", "bailable": False, "cognizable": True, "keywords": ["dowry death", "bride burning", "dowry murder", "matrimonial death"]},
    {"section": "IPC 504", "title": "Intentional insult with intent to provoke breach of the peace", "description": "Whoever intentionally insults, and thereby gives provocation to any person, intending or knowing it to be likely that such provocation will cause him to break the public peace, or to commit any other offence.", "punishment": "Up to 2 years or fine or both", "bailable": True, "cognizable": False, "keywords": ["insult", "provocation", "abusing", "verbal abuse", "intentional insult"]},
    {"section": "IPC 506", "title": "Punishment for criminal intimidation", "description": "Whoever commits the offence of criminal intimidation shall be punished with imprisonment for a term which may extend to two years, or with fine, or with both; and if the threat be to cause death or grievous hurt, or to cause the destruction of any property by fire, shall be punished with imprisonment for a term which may extend to seven years.", "punishment": "Up to 2 years or fine; up to 7 years for serious threats", "bailable": True, "cognizable": False, "keywords": ["threat", "intimidation", "threatening", "criminal threat", "coercion"]},
    {"section": "IPC 509", "title": "Word, gesture or act intended to insult the modesty of a woman", "description": "Whoever, intending to insult the modesty of any woman, utters any word, makes any sound or gesture, or exhibits any object, intending that such word or sound shall be heard, or that such gesture or object shall be seen, by such woman.", "punishment": "Up to 3 years + fine", "bailable": True, "cognizable": False, "keywords": ["eve teasing", "sexual comments", "modesty insult", "catcalling", "verbal sexual harassment"]},
    {"section": "IPC 147", "title": "Punishment for rioting", "description": "Whoever is guilty of rioting, shall be punished with imprisonment for a term which may extend to two years, or with fine, or with both.", "punishment": "Up to 2 years or fine or both", "bailable": True, "cognizable": True, "keywords": ["riot", "rioting", "public disorder", "mob violence", "unlawful assembly"]},
    {"section": "IPC 148", "title": "Rioting, armed with deadly weapon", "description": "Whoever is guilty of rioting, being armed with a deadly weapon or with anything which, used as a weapon of offence, is likely to cause death, shall be punished with imprisonment for a term which may extend to three years, or with fine, or with both.", "punishment": "Up to 3 years or fine or both", "bailable": False, "cognizable": True, "keywords": ["armed rioting", "rioting with weapon", "mob with weapons", "communal violence"]},
    {"section": "IPC 201", "title": "Causing disappearance of evidence of offence", "description": "Whoever, knowing or having reason to believe that an offence has been committed, causes any evidence of the commission of that offence to disappear, with the intention of screening the offender from legal punishment.", "punishment": "Imprisonment up to the maximum provided for the screened offence", "bailable": None, "cognizable": None, "keywords": ["evidence destruction", "concealing evidence", "obstruction of justice", "tampering with evidence"]},
    {"section": "IPC 182", "title": "False information, with intent to cause public servant to use his lawful power", "description": "Whoever gives to any public servant any information which he knows or believes to be false, intending thereby to cause, or knowing it to be likely that he will thereby cause, such public servant to use the lawful power of such public servant.", "punishment": "Up to 6 months or fine up to Rs. 1000 or both", "bailable": True, "cognizable": False, "keywords": ["false complaint", "false FIR", "false information", "misleading police"]},
]

CASE_PRECEDENTS = [
    {"case_name": "Bachan Singh v. State of Punjab", "citation": "AIR 1980 SC 898", "court": "Supreme Court of India", "year": 1980, "judges": ["Y.V. Chandrachud CJ", "A.C. Gupta J", "N.L. Untwalia J", "P.N. Bhagwati J", "R.S. Sarkaria J"], "facts": "Constitutional validity of the death penalty under Section 302 IPC read with Section 354(3) CrPC was challenged. The question was whether the death penalty was violative of Articles 14, 19 and 21 of the Constitution.", "held": "The death penalty is constitutionally valid but must be imposed only in the 'rarest of rare' cases where the alternative of life imprisonment is unquestionably foreclosed. The court laid down guidelines for when death penalty may be imposed.", "legal_principle": "Death penalty permissible only in 'rarest of rare' cases — a case which, when observed, the collective conscience of the community is so shocked that it expects holders of judicial power to inflict death penalty.", "relevant_sections": ["IPC 302", "CrPC 354(3)"], "keywords": ["death penalty", "rarest of rare", "capital punishment", "murder sentencing", "life imprisonment"]},
    {"case_name": "Maneka Gandhi v. Union of India", "citation": "AIR 1978 SC 597", "court": "Supreme Court of India", "year": 1978, "judges": ["M.H. Beg CJ", "Y.V. Chandrachud J", "V.R. Krishna Iyer J", "P.N. Bhagwati J", "N.L. Untwalia J", "S. Murtaza Fazal Ali J", "P.S. Kailasam J"], "facts": "Petitioner's passport was impounded by the Government without giving her any opportunity to be heard. The question was whether this violated her fundamental rights under Articles 14, 19 and 21.", "held": "The right to live is not merely confined to physical existence but includes the right to live with human dignity. The procedure established by law must be fair, just and reasonable. The three Articles 14, 19 and 21 are not mutually exclusive and must be read together.", "legal_principle": "Right to life under Article 21 includes right to live with dignity. Any law depriving life/liberty must be fair, just, and reasonable. Articles 14, 19, and 21 form a golden triangle.", "relevant_sections": ["Constitution Article 21", "Constitution Article 14", "Constitution Article 19"], "keywords": ["right to life", "personal liberty", "due process", "natural justice", "fundamental rights", "Article 21"]},
    {"case_name": "K.M. Nanavati v. State of Maharashtra", "citation": "AIR 1962 SC 605", "court": "Supreme Court of India", "year": 1962, "judges": ["B.P. Sinha CJ", "A.K. Sarkar J", "K.C. Das Gupta J", "N. Rajagopala Ayyangar J", "J.C. Shah J"], "facts": "Naval Commander Nanavati shot and killed Prem Ahuja, his wife's lover, after confronting him. He was tried by jury which returned a verdict of not guilty, but the Sessions Judge referred the case to the High Court. The High Court convicted him.", "held": "The Supreme Court upheld the conviction for murder under Section 302 IPC. The concept of 'grave and sudden provocation' was not applicable as the accused had time to think and plan. The verdict led to the abolition of the jury system in India.", "legal_principle": "Provocation must be grave AND sudden. If the accused had time to cool down and plan the act, the defence of provocation fails. Exception 1 to Section 300 IPC strictly interpreted.", "relevant_sections": ["IPC 300", "IPC 302"], "keywords": ["provocation", "grave sudden provocation", "murder", "exception 300 IPC", "jury system abolition"]},
    {"case_name": "Hussainara Khatoon v. State of Bihar", "citation": "AIR 1979 SC 1360", "court": "Supreme Court of India", "year": 1979, "judges": ["P.N. Bhagwati J"], "facts": "A newspaper article revealed that thousands of undertrial prisoners in Bihar were languishing in jails for periods longer than the maximum sentence for the offences they were charged with. A writ petition was filed for their release.", "held": "Right to speedy trial is a fundamental right under Article 21. Undertrial prisoners cannot be kept in jail for periods longer than the maximum sentence for the offence. Courts must ensure speedy justice. The concept of public interest litigation was significantly developed.", "legal_principle": "Speedy trial is an essential component of right to life and liberty under Article 21. Indefinite detention of undertrials is unconstitutional. PIL was recognized as an important tool for constitutional remedy.", "relevant_sections": ["Constitution Article 21", "Constitution Article 22"], "keywords": ["speedy trial", "undertrial prisoners", "bail", "Article 21", "right to liberty", "PIL", "public interest litigation"]},
    {"case_name": "Vishaka v. State of Rajasthan", "citation": "AIR 1997 SC 3011", "court": "Supreme Court of India", "year": 1997, "judges": ["J.S. Verma CJ", "Sujata V. Manohar J", "B.N. Kirpal J"], "facts": "Bhanwari Devi, a social worker, was gang-raped for preventing a child marriage. The case highlighted the absence of legislation protecting women from sexual harassment at the workplace.", "held": "In the absence of legislation, the Supreme Court issued 'Vishaka Guidelines' for protection of women against sexual harassment at the workplace. These guidelines were made legally binding until appropriate legislation was enacted. The POSH Act 2013 later codified these guidelines.", "legal_principle": "Employer has constitutional duty to protect female employees from sexual harassment. In absence of legislation, judicial guidelines are binding under Article 141. The Vishaka Guidelines became the foundation of POSH Act 2013.", "relevant_sections": ["IPC 354", "IPC 376", "Constitution Article 14", "Constitution Article 15", "Constitution Article 21"], "keywords": ["sexual harassment", "workplace harassment", "Vishaka guidelines", "POSH act", "women protection", "fundamental rights"]},
    {"case_name": "State of Maharashtra v. Madhurkar Narayan Mardikar", "citation": "AIR 1991 SC 207", "court": "Supreme Court of India", "year": 1991, "judges": ["K.N. Singh J", "S. Ranganathan J"], "facts": "A police officer was acquitted of charges of rape despite victim's testimony. The sessions court and high court held that the victim was a woman of 'easy virtue' and hence the officer was acquitted.", "held": "Even a woman of easy virtue is entitled to privacy and no one can violate it. Past sexual conduct of a woman cannot be used to discredit her testimony in rape cases. The right to privacy and dignity is inviolable.", "legal_principle": "A woman's past sexual conduct is irrelevant to the question of whether rape occurred. Every woman, regardless of her character or occupation, has a right to dignity and bodily integrity.", "relevant_sections": ["IPC 376", "Indian Evidence Act Section 155(4)"], "keywords": ["rape", "victim character", "sexual assault", "women dignity", "victim blaming", "past conduct irrelevant"]},
    {"case_name": "Arnesh Kumar v. State of Bihar", "citation": "(2014) 8 SCC 273", "court": "Supreme Court of India", "year": 2014, "judges": ["Chandramauli Kumar Prasad J", "Pinaki Chandra Ghose J"], "facts": "The petitioner was sought to be arrested by his wife under IPC Section 498A without proper investigation. The question was whether arrest could be made mechanically in cases under Section 498A.", "held": "Police officers cannot arrest accused automatically in cases under IPC 498A. Magistrates cannot authorize detention mechanically. A check-list of conditions must be satisfied before arrest. The judgment aimed to prevent misuse of Section 498A.", "legal_principle": "Arrest is not automatic; it is last resort. Police and magistrates must apply their minds. Seven categories from Section 41(1)(b) CrPC must be considered. Section 498A should not be weaponized.", "relevant_sections": ["IPC 498A", "CrPC 41", "CrPC 41A"], "keywords": ["arrest", "498A misuse", "dowry harassment", "pre-arrest", "personal liberty", "magistrate authorization"]},
    {"case_name": "Lalita Kumari v. Government of UP", "citation": "(2014) 2 SCC 1", "court": "Supreme Court of India", "year": 2014, "judges": ["P. Sathasivam CJ", "B.S. Chauhan J", "Ranjana Prakash Desai J", "Ranjan Gogoi J", "S.A. Bobde J"], "facts": "Constitutional validity of mandatory registration of FIR under Section 154 CrPC was questioned. Several High Courts had taken different views on whether registration of FIR was mandatory.", "held": "Registration of FIR is mandatory if the information discloses a cognizable offence. Police have no discretion to conduct preliminary inquiry in such cases. However, in cases where prima facie no cognizable offence is made out, preliminary inquiry may be conducted.", "legal_principle": "FIR registration is mandatory for cognizable offences under Section 154 CrPC. Police officer has no discretion to refuse registration. Preliminary inquiry permitted only in limited categories.", "relevant_sections": ["CrPC 154", "CrPC 156"], "keywords": ["FIR", "mandatory registration", "cognizable offence", "police duty", "first information report"]},
    {"case_name": "Sharad Birdhichand Sarda v. State of Maharashtra", "citation": "AIR 1984 SC 1622", "court": "Supreme Court of India", "year": 1984, "judges": ["Fazal Ali J", "A. Varadarajan J"], "facts": "The accused was convicted for murder of his wife based purely on circumstantial evidence. The question was the standard of proof required in cases based on circumstantial evidence.", "held": "The court laid down five golden rules ('Panchasheel') for conviction based on circumstantial evidence: 1. The circumstances from which the conclusion of guilt is to be drawn must be fully established; 2. The facts so established must be consistent only with the hypothesis of guilt; 3. The circumstances must be of a conclusive nature; 4. They must exclude every possible hypothesis except the one to be proved; 5. There must be a chain of evidence so complete as not to leave any reasonable doubt.", "legal_principle": "The Panchasheel test: For conviction on circumstantial evidence, the chain of circumstances must be so complete that it points unerringly to the guilt of the accused and excludes all other reasonable hypotheses.", "relevant_sections": ["IPC 302", "Indian Evidence Act"], "keywords": ["circumstantial evidence", "Panchasheel", "murder proof", "chain of evidence", "reasonable doubt"]},
    {"case_name": "Mohammed Ahmed Khan v. Shah Bano Begum", "citation": "AIR 1985 SC 945", "court": "Supreme Court of India", "year": 1985, "judges": ["Y.V. Chandrachud CJ"], "facts": "Shah Bano, a 73-year-old Muslim woman, was divorced by her husband and sought maintenance under Section 125 CrPC. The question was whether Section 125 CrPC applied to Muslim divorced women.", "held": "Section 125 CrPC is applicable to all women regardless of religion. Muslim divorced women are entitled to maintenance beyond the iddat period if they are unable to maintain themselves. This decision was subsequently overruled by the Muslim Women (Protection of Rights on Divorce) Act, 1986.", "legal_principle": "Section 125 CrPC is a secular provision applicable to all women. Courts have duty to apply uniform law regardless of religion. Rights of women to maintenance transcend religious personal laws.", "relevant_sections": ["CrPC 125", "Muslim Personal Law"], "keywords": ["maintenance", "Muslim divorce", "Shah Bano", "secular law", "CrPC 125", "alimony", "uniform civil code"]},
    {"case_name": "Naz Foundation v. Government of NCT of Delhi", "citation": "(2009) 160 DLT 277", "court": "Delhi High Court", "year": 2009, "judges": ["A.P. Shah CJ", "S. Muralidhar J"], "facts": "The constitutional validity of Section 377 IPC (unnatural offences) was challenged as violating the fundamental rights of LGBT persons. The petition was filed by Naz Foundation, an NGO.", "held": "Section 377 IPC insofar as it criminalizes consensual sexual acts of adults in private, is violative of Articles 14, 15, 19 and 21 of the Constitution. The right to dignity, equality and privacy cannot be denied on the basis of sexual orientation.", "legal_principle": "Sexual orientation is an inherent and immutable part of identity. Consensual private adult acts cannot be criminalized. Constitutional morality must override social morality.", "relevant_sections": ["IPC 377", "Constitution Article 14", "Constitution Article 21"], "keywords": ["Section 377", "LGBT rights", "homosexuality", "decriminalization", "constitutional morality", "privacy rights"]},
    {"case_name": "K.S. Puttaswamy v. Union of India", "citation": "(2017) 10 SCC 1", "court": "Supreme Court of India", "year": 2017, "judges": ["9-Judge Constitution Bench"], "facts": "Constitutional validity of Aadhaar was challenged. Preliminary issue was whether right to privacy is a fundamental right under the Constitution. The government argued that there is no fundamental right to privacy based on earlier judgments.", "held": "Right to Privacy is a fundamental right under Article 21 of the Constitution. The earlier judgments of M.P. Sharma and Kharak Singh (which held to the contrary) were overruled. Privacy includes bodily integrity, personal autonomy, informational privacy, and decisional autonomy.", "legal_principle": "Privacy is a fundamental right. It encompasses informational privacy, bodily integrity, and personal autonomy. State must justify any intrusion into privacy by demonstrating legality, legitimate aim, and proportionality.", "relevant_sections": ["Constitution Article 21", "Constitution Article 14", "Constitution Article 19"], "keywords": ["right to privacy", "Aadhaar", "data protection", "personal liberty", "informational privacy", "fundamental right"]},
    {"case_name": "Indira Sawhney v. Union of India", "citation": "AIR 1993 SC 477", "court": "Supreme Court of India", "year": 1993, "judges": ["9-Judge Constitution Bench"], "facts": "The Mandal Commission Report recommending 27% reservation for OBCs in central government services was challenged. Various aspects of the reservation policy including the 50% cap were considered.", "held": "Reservations for OBCs is constitutionally valid but total reservations cannot exceed 50% except in extraordinary circumstances. 'Creamy layer' concept applied — advanced members of OBC community should be excluded from reservations. Reservations cannot be applied to promotions.", "legal_principle": "Total reservation cannot exceed 50% rule. Creamy layer concept: Economically advanced members of OBC should not get reservation benefits. Reservation is a tool for equalization, not a permanent feature.", "relevant_sections": ["Constitution Article 16(4)", "Constitution Article 15"], "keywords": ["reservation", "OBC", "Mandal commission", "creamy layer", "50% cap", "affirmative action"]},
    {"case_name": "D.K. Basu v. State of West Bengal", "citation": "AIR 1997 SC 610", "court": "Supreme Court of India", "year": 1997, "judges": ["A.S. Anand J", "Kuldip Singh J"], "facts": "A letter written by an advocate highlighting deaths in police custody was treated as a writ petition. The question was what safeguards should be provided to persons arrested by police.", "held": "The court laid down 11 specific requirements to be followed in all cases of arrest and detention: memo of arrest, informing relatives, medical examination, right to meet advocate, etc. Custodial torture is a violation of Article 21.", "legal_principle": "Custodial death and torture are grave violations of fundamental rights. Police must follow strict procedural safeguards during arrest. Violation of these safeguards would not only affect prosecution case but also render officers liable.", "relevant_sections": ["Constitution Article 21", "CrPC 41", "CrPC 54"], "keywords": ["custodial death", "police torture", "arrest guidelines", "D.K. Basu guidelines", "custody rights", "fundamental rights during arrest"]},
    {"case_name": "Pratap Dixit v. State of UP", "citation": "(2019) 5 SCC 104", "court": "Supreme Court of India", "year": 2019, "judges": ["N.V. Ramana J", "Mohan M. Shantanagoudar J"], "facts": "The accused was convicted for attempt to murder. The question was whether the provisions for bail under Section 439 CrPC were correctly applied by the courts below.", "held": "While granting bail, courts must consider: (1) the nature and gravity of accusation; (2) antecedents of the accused; (3) possibility of accused fleeing justice; (4) possibility of tampering with evidence; (5) safety of society. Bail is rule, jail is exception for bailable offences.", "legal_principle": "Bail jurisprudence: Courts must balance personal liberty with societal interest. Factors for bail include flight risk, tampering, gravity of offence. Personal liberty under Article 21 must be respected.", "relevant_sections": ["CrPC 437", "CrPC 439", "Constitution Article 21"], "keywords": ["bail", "personal liberty", "bail factors", "flight risk", "evidence tampering", "bail jurisprudence"]},
    {"case_name": "State of Rajasthan v. Balchand", "citation": "AIR 1977 SC 2447", "court": "Supreme Court of India", "year": 1977, "judges": ["V.R. Krishna Iyer J"], "facts": "The accused was convicted and sentenced to imprisonment. The question was whether bail could be granted pending appeal and what factors should guide the court.", "held": "Bail is the rule and jail is the exception. The court should lean in favour of granting bail unless there are compelling circumstances to justify detention. The purpose of bail is to ensure appearance at trial, not to punish.", "legal_principle": "Bail is the rule, jail is exception — landmark statement by Justice V.R. Krishna Iyer. Courts should not deny bail mechanically. Personal liberty is precious and not to be compromised without compelling reasons.", "relevant_sections": ["CrPC 437", "CrPC 438", "CrPC 439"], "keywords": ["bail", "bail is rule", "personal liberty", "pre-trial detention", "anticipatory bail"]},
    {"case_name": "Moti Ram v. State of Madhya Pradesh", "citation": "AIR 1978 SC 1594", "court": "Supreme Court of India", "year": 1978, "judges": ["V.R. Krishna Iyer J"], "facts": "An undertrial prisoner could not furnish surety for bail due to poverty. The question was whether a poor person could be denied bail merely because he could not afford surety.", "held": "A poor person cannot be denied bail merely because he cannot furnish surety. The court has power to release a person on personal bond without sureties. The bail provisions must be applied in a manner consistent with Article 21.", "legal_principle": "Poverty cannot be a reason to deny bail. Courts have power to grant bail on personal recognizance without sureties. Access to justice cannot be denied to the poor.", "relevant_sections": ["CrPC 437", "Constitution Article 21"], "keywords": ["bail", "poor accused", "surety", "personal bond", "access to justice", "poverty and bail"]},
    {"case_name": "R v. R (Husband's Immunity from Prosecution for Rape)", "citation": "(1991) 4 All ER 481", "court": "House of Lords", "year": 1991, "judges": ["Lord Keith", "Lord Brandon", "Lord Griffiths", "Lord Ackner", "Lord Lane"], "facts": "A husband was charged with rape and attempted rape of his wife during the breakdown of their marriage. The husband relied on the old common law rule that a husband could not be guilty of raping his wife.", "held": "The old common law fiction that a wife on marriage gives irrevocable consent to sexual intercourse by her husband was abolished. A husband can be convicted of raping his wife. The marital rape exception is inconsistent with modern family law and human rights.", "legal_principle": "Marital rape is a crime. There is no immunity for spouses from sexual assault charges. This case influenced Indian debates on marital rape, which remains a contested issue in India.", "relevant_sections": ["IPC 376"], "keywords": ["marital rape", "spousal rape", "consent", "marriage immunity", "sexual assault in marriage"]},
    {"case_name": "Joginder Kumar v. State of UP", "citation": "AIR 1994 SC 1349", "court": "Supreme Court of India", "year": 1994, "judges": ["M.N. Venkatachaliah CJ", "J.S. Verma J"], "facts": "An advocate was arrested and detained without reason or notice to family members. The case highlighted arbitrary police arrests.", "held": "No arrest can be made merely because it is lawful for the police to do so. There must be justification for making the arrest. The arrested person has the right to be informed of the grounds of arrest and to meet his lawyer. Family/friends must be informed of the arrest.", "legal_principle": "Arrest power must be exercised with care and circumspection. Police officer is accountable for every arrest. Rights of arrested person include: knowing reasons for arrest, right to advocate, informing relatives.", "relevant_sections": ["Constitution Article 21", "Constitution Article 22", "CrPC 41"], "keywords": ["illegal arrest", "arbitrary detention", "arrest rights", "police accountability", "right to advocate on arrest"]},
    {"case_name": "Suresh Kumar Koushal v. Naz Foundation", "citation": "(2014) 1 SCC 1", "court": "Supreme Court of India", "year": 2014, "judges": ["G.S. Singhvi J", "S.J. Mukhopadhaya J"], "facts": "The Supreme Court was hearing an appeal against the Delhi High Court's 2009 judgment which had decriminalized consensual same-sex acts between adults under Section 377 IPC.", "held": "The Supreme Court reversed the Delhi High Court judgment and held that Section 377 IPC is constitutionally valid. The Court held that a 'miniscule minority' cannot be used to strike down a law. This judgment was subsequently overruled in Navtej Singh Johar (2018).", "legal_principle": "Subsequently overruled — minority rights cannot be disregarded. This case demonstrates how the Supreme Court can revisit and overrule its own decisions in light of evolving constitutional values.", "relevant_sections": ["IPC 377"], "keywords": ["Section 377", "LGBT", "overruled judgment", "minority rights", "constitutional evolution"]},
    {"case_name": "Navtej Singh Johar v. Union of India", "citation": "(2018) 10 SCC 1", "court": "Supreme Court of India", "year": 2018, "judges": ["Dipak Misra CJ", "A.M. Khanwilkar J", "R.F. Nariman J", "D.Y. Chandrachud J", "Indu Malhotra J"], "facts": "Section 377 IPC criminalizing consensual same-sex acts between adults was challenged. The petitioners included several prominent persons from the LGBTQ community.", "held": "Consensual same-sex acts between adults are decriminalized. Section 377 IPC is read down to exclude consensual acts between adults. The Suresh Kumar Koushal judgment was overruled. Sexual orientation is an inherent part of identity.", "legal_principle": "Constitutional morality supersedes social morality. LGBTQ persons have equal rights to dignity, privacy and equality. Consent and adult autonomy are central to constitutional freedoms.", "relevant_sections": ["IPC 377", "Constitution Article 14", "Constitution Article 15", "Constitution Article 21"], "keywords": ["Section 377 decriminalized", "LGBT rights", "consent", "sexual orientation", "constitutional morality", "dignity"]},
    {"case_name": "Gian Kaur v. State of Punjab", "citation": "AIR 1996 SC 946", "court": "Supreme Court of India", "year": 1996, "judges": ["J.S. Verma CJ", "5-Judge Constitution Bench"], "facts": "Constitutional validity of Sections 306 (abetment of suicide) and 309 (attempt to suicide) IPC was challenged on the ground that they violated Article 21.", "held": "Right to life under Article 21 does not include right to die. Section 309 IPC (attempt to suicide) is constitutional. Right to die with dignity is different from right to die. Euthanasia and assisted suicide remain a separate question.", "legal_principle": "Right to life under Article 21 does not include right to extinguish it. Suicide and its abetment are criminal acts. Right to die with dignity (natural death) was later recognized in Aruna Shanbaug case.", "relevant_sections": ["IPC 306", "IPC 309", "Constitution Article 21"], "keywords": ["right to die", "suicide", "euthanasia", "right to life", "attempt to suicide", "abetment of suicide"]},
    {"case_name": "State of Haryana v. Bhajan Lal", "citation": "AIR 1992 SC 604", "court": "Supreme Court of India", "year": 1992, "judges": ["S.S. Ahmadi J", "K. Jayachandra Reddy J"], "facts": "The question was whether the High Court can quash an FIR and when such power should be exercised under Section 482 CrPC.", "held": "The Supreme Court laid down seven categories of cases where FIR/criminal proceedings may be quashed: (1) Allegations do not constitute any offence; (2) Allegations are absurd; (3) Where there is a legal bar; (4) Where proceedings are mala fide; etc.", "legal_principle": "FIR can be quashed under Section 482 CrPC in exceptional circumstances. The power of High Court to quash FIR is wide but should be exercised sparingly. Seven categories of quashable FIRs were enumerated.", "relevant_sections": ["CrPC 154", "CrPC 482"], "keywords": ["quashing FIR", "CrPC 482", "inherent powers", "quash criminal proceedings", "Bhajan Lal guidelines"]},
    {"case_name": "Sushil Kumar Sharma v. Union of India", "citation": "AIR 2005 SC 3100", "court": "Supreme Court of India", "year": 2005, "judges": ["Y.K. Sabharwal J", "D.M. Dharmadhikari J"], "facts": "A petition was filed questioning the misuse of IPC Section 498A by disgruntled wives to harass husbands and their families with false cases. Statistics showed high rates of acquittal and filing of false cases.", "held": "The existence of Section 498A and its misuse cannot be a ground to strike it down. However, the court acknowledged the misuse and directed that police should be careful in making arrests. The law is for protection of women and cannot be used as a tool for vengeance.", "legal_principle": "A law that is valid cannot be struck down merely because it is misused. However, misuse of Section 498A to harass innocent family members must be checked. Courts must guard against false cases.", "relevant_sections": ["IPC 498A"], "keywords": ["498A misuse", "false dowry cases", "domestic violence misuse", "husband harassment", "matrimonial law abuse"]},
    {"case_name": "P. Ramachandra Rao v. State of Karnataka", "citation": "(2002) 4 SCC 578", "court": "Supreme Court of India", "year": 2002, "judges": ["5-Judge Constitution Bench"], "facts": "The question was whether courts can fix time limits for completion of criminal trials as a remedy for violation of the right to speedy trial under Article 21.", "held": "Courts cannot fix a blanket time limit for completion of criminal trials. However, in individual cases, courts can take steps to expedite trial. The right to speedy trial is a fundamental right but it must be balanced with the needs of justice.", "legal_principle": "No blanket time limit for criminal trials but right to speedy trial must be ensured case by case. Delayed trial is a violation of Article 21. Remedy is within the legal framework, not by fixing arbitrary time limits.", "relevant_sections": ["Constitution Article 21", "CrPC 309"], "keywords": ["speedy trial", "delayed trial", "Article 21", "right to fair trial", "criminal trial duration"]},
]

SUPREME_COURT_JUDGMENTS = [
    {"case_name": "Joseph Shine v. Union of India", "citation": "(2019) 3 SCC 39", "court": "Supreme Court of India", "year": 2018, "bench_strength": 5, "coram": ["Dipak Misra CJ", "A.M. Khanwilkar J", "R.F. Nariman J", "D.Y. Chandrachud J", "Indu Malhotra J"], "area_of_law": "Criminal Law — Adultery", "summary": "Struck down IPC Section 497 (adultery) as unconstitutional. The court held that the provision was archaic, paternalistic, and treated women as property of their husbands. Adultery was decriminalized.", "key_ratio": "Adultery cannot be a criminal offence. Women are not chattel of their husbands. The law violated Articles 14, 15, and 21 of the Constitution.", "impact": "IPC Section 497 was struck down. Adultery may still be a ground for civil matrimonial remedies but is no longer a criminal offence."},
    {"case_name": "Shafin Jahan v. Asokan K.M.", "citation": "(2018) 16 SCC 368", "court": "Supreme Court of India", "year": 2018, "bench_strength": 3, "coram": ["Dipak Misra CJ", "A.M. Khanwilkar J", "D.Y. Chandrachud J"], "area_of_law": "Constitutional Law — Marriage and Personal Liberty", "summary": "The Supreme Court restored the marriage of Hadiya (formerly Akhila) with Shafin Jahan, overruling the Kerala HC's annulment. The court held that the right to choose a partner is a fundamental right under Article 21.", "key_ratio": "Right to choose a partner for marriage is a fundamental right. Courts cannot annul marriages of adults based on parental objection or religious conversion allegations.", "impact": "Reinforced right to marry a person of one's choice regardless of religion."},
    {"case_name": "Common Cause v. Union of India (Passive Euthanasia)", "citation": "(2018) 5 SCC 1", "court": "Supreme Court of India", "year": 2018, "bench_strength": 5, "coram": ["Dipak Misra CJ", "A.K. Sikri J", "A.M. Khanwilkar J", "D.Y. Chandrachud J", "Ashok Bhushan J"], "area_of_law": "Constitutional Law — Right to Die with Dignity", "summary": "Passive euthanasia recognized as a part of right to live with dignity under Article 21. The court upheld the right of a person to create a living will (advance medical directive) to refuse treatment in case of terminal illness.", "key_ratio": "Right to die with dignity is a fundamental right under Article 21. Passive euthanasia and advance directives are legal. The dignity of death is as important as dignity of life.", "impact": "Advance medical directives (living wills) are legally valid in India."},
    {"case_name": "Shayara Bano v. Union of India (Triple Talaq)", "citation": "(2017) 9 SCC 1", "court": "Supreme Court of India", "year": 2017, "bench_strength": 5, "coram": ["J.S. Khehar CJ", "Kurian Joseph J", "R.F. Nariman J", "U.U. Lalit J", "S. Abdul Nazeer J"], "area_of_law": "Personal Law — Muslim Divorce", "summary": "Triple talaq (talaq-e-biddat) was declared unconstitutional by 3:2 majority. The practice of instant triple talaq was held to be manifestly arbitrary and violative of Article 14.", "key_ratio": "Triple talaq is unconstitutional as it is manifestly arbitrary and violates dignity of Muslim women. What is bad in theology cannot be good in law.", "impact": "The Muslim Women (Protection of Rights on Marriage) Act 2019 subsequently criminalized triple talaq."},
    {"case_name": "Indian Young Lawyers Association v. State of Kerala (Sabarimala)", "citation": "(2019) 11 SCC 1", "court": "Supreme Court of India", "year": 2018, "bench_strength": 5, "coram": ["Dipak Misra CJ", "A.M. Khanwilkar J", "R.F. Nariman J", "D.Y. Chandrachud J", "Indu Malhotra J"], "area_of_law": "Constitutional Law — Religion and Equality", "summary": "The prohibition on entry of women of menstruating age (10-50 years) to the Sabarimala temple was struck down as unconstitutional. All women have the right to enter temples regardless of age or physiological conditions.", "key_ratio": "Physiological characteristics cannot be grounds for exclusion. Devotion cannot be subjected to biological restrictions. Exclusion of women from temple is unconstitutional.", "impact": "Women of all ages now have legal right to enter Sabarimala temple, though implementation faced significant public resistance."},
    {"case_name": "Pam Developments Pvt. Ltd. v. State of West Bengal", "citation": "(2019) 8 SCC 112", "court": "Supreme Court of India", "year": 2019, "bench_strength": 2, "coram": ["S.A. Nazeer J", "Sanjiv Khanna J"], "area_of_law": "Commercial Law — Arbitration", "summary": "The Supreme Court held that the limitation period for challenging arbitral awards under Section 34 of the Arbitration Act cannot be extended by courts under Section 5 of the Limitation Act. The three-month period plus 30 days is an absolute outer limit.", "key_ratio": "Limitation period for challenging arbitral awards is strictly mandatory. Courts cannot extend time beyond the outer limit prescribed under Section 34(3) of the Arbitration Act.", "impact": "Significant impact on commercial arbitration. Parties must file challenges within strict time limits."},
    {"case_name": "Sonu Gupta v. Dipak Gupta", "citation": "(2021) 4 SCC 540", "court": "Supreme Court of India", "year": 2021, "bench_strength": 3, "coram": ["Sanjay Kishan Kaul J", "Dinesh Maheshwari J", "Hrishikesh Roy J"], "area_of_law": "Family Law — Divorce", "summary": "The Supreme Court exercised its power under Article 142 to dissolve a marriage on grounds of irretrievable breakdown — even though this ground is not expressly available under the Hindu Marriage Act. The court held that in exceptional cases of long separation, Article 142 can be used.", "key_ratio": "Irretrievable breakdown of marriage can be a ground for divorce under Article 142 of the Constitution. Courts can exercise constitutional power to do complete justice.", "impact": "Courts can grant divorce in exceptional cases using Article 142 even without statutory ground."},
    {"case_name": "Rupa Ashok Hurra v. Ashok Hurra", "citation": "AIR 2002 SC 1771", "court": "Supreme Court of India", "year": 2002, "bench_strength": 5, "coram": ["G.B. Pattanaik CJ", "S.S.M. Quadri J", "Y.K. Sabharwal J", "Ruma Pal J", "Shivaraj V. Patil J"], "area_of_law": "Constitutional Law — Curative Petition", "summary": "The Supreme Court recognized the concept of 'Curative Petition' — a petition that can be filed even after a review petition is dismissed. This is the last judicial remedy before the Supreme Court.", "key_ratio": "The Supreme Court can reconsider its own final judgment after review is dismissed, in exceptional circumstances to prevent gross miscarriage of justice.", "impact": "Curative petitions are now a recognized last-resort remedy before the Supreme Court."},
    {"case_name": "State of UP v. Not Reported — Section 438 CrPC Anticipatory Bail", "citation": "(2019) 7 SCC 1", "court": "Supreme Court of India", "year": 2019, "bench_strength": 3, "coram": ["Arun Mishra J", "Indira Banerjee J", "M.R. Shah J"], "area_of_law": "Criminal Procedure — Anticipatory Bail", "summary": "The Supreme Court held that anticipatory bail under Section 438 CrPC can be granted without time limitation. Earlier practice of granting anticipatory bail only till filing of chargesheet was deprecated.", "key_ratio": "Anticipatory bail operates till the end of trial unless cancelled by court. Courts should not impose blanket time limits on anticipatory bail.", "impact": "Changed the practice of courts that used to routinely limit anticipatory bail to the period till chargesheet filing."},
    {"case_name": "Lily Thomas v. Union of India", "citation": "(2013) 7 SCC 653", "court": "Supreme Court of India", "year": 2013, "bench_strength": 2, "coram": ["S.J. Mukhopadhaya J", "Dipak Misra J"], "area_of_law": "Electoral Law — Disqualification of Legislators", "summary": "Any sitting MP or MLA convicted of any offence and sentenced to minimum 2 years imprisonment is immediately disqualified from holding office. The provision in Section 8(4) of the Representation of People Act allowing convicted legislators to continue in office pending appeal was struck down.", "key_ratio": "Convicted legislators stand immediately disqualified. The law cannot discriminate between a sitting member and a new candidate. There is no stay on disqualification.", "impact": "Major electoral reform. Several sitting MPs and MLAs have been disqualified pursuant to this ruling."},
    {"case_name": "NALSA v. Union of India (Transgender Rights)", "citation": "(2014) 5 SCC 438", "court": "Supreme Court of India", "year": 2014, "bench_strength": 2, "coram": ["K.S. Radhakrishnan J", "A.K. Sikri J"], "area_of_law": "Constitutional Law — Transgender Rights", "summary": "Transgender persons were recognized as a 'third gender'. Their right to self-identification of gender was recognized as a fundamental right. Government was directed to grant reservations and other benefits to transgenders as a socially and educationally backward class.", "key_ratio": "Third gender is recognized as a legal category. Self-identified gender must be respected by the State. Transgender persons have fundamental rights to equality and dignity.", "impact": "Paved the way for the Transgender Persons (Protection of Rights) Act 2019."},
]


def build_ipc_sections():
    path = LEGAL_DB / "ipc_sections.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(IPC_SECTIONS, f, indent=2, ensure_ascii=False)
    print(f"  [✓] ipc_sections.json — {len(IPC_SECTIONS)} sections written")


def build_crpc_sections():
    crpc = [
        {"section": "CrPC 41", "title": "When police may arrest without warrant", "description": "A police officer may without an order from a Magistrate and without a warrant, arrest any person who has been concerned in any cognizable offence, or against whom a reasonable complaint has been made or credible information has been received.", "keywords": ["arrest", "without warrant", "police powers", "cognizable offence"]},
        {"section": "CrPC 41A", "title": "Notice of appearance before police officer", "description": "The police officer shall, in all cases where the arrest of a person is not required under the provisions of sub-section (1) of section 41, issue a notice directing the person against whom a reasonable complaint has been made.", "keywords": ["notice", "appearance", "alternatives to arrest", "non-arrest"]},
        {"section": "CrPC 154", "title": "Information in cognizable cases", "description": "Every information relating to the commission of a cognizable offence, if given orally to an officer in charge of a police station, shall be reduced to writing by him or under his direction, and be read over to the informant.", "keywords": ["FIR", "first information report", "cognizable offence", "police station", "registration"]},
        {"section": "CrPC 156", "title": "Police officer's power to investigate cognizable case", "description": "Any officer in charge of a police station may, without the order of a Magistrate, investigate any cognizable case which a Court having jurisdiction over the local area within the limits of such station would have power to inquire into or try.", "keywords": ["investigation", "cognizable case", "police power", "without magistrate order"]},
        {"section": "CrPC 161", "title": "Examination of witnesses by police", "description": "Any police officer making an investigation under this Chapter, or any police officer not below such rank as the State Government may, by general or special order, prescribe in this behalf, acting on the requisition of such officer, may examine orally any person.", "keywords": ["witness examination", "police investigation", "statement", "Section 161 statement"]},
        {"section": "CrPC 164", "title": "Recording of confessions and statements", "description": "Any Metropolitan Magistrate or Judicial Magistrate may, whether or not he has jurisdiction in the case, record any confession or statement made to him in the course of an investigation under this Chapter or under any other law.", "punishment": "N/A — procedural", "keywords": ["confession", "magistrate confession", "Section 164 statement", "recorded statement"]},
        {"section": "CrPC 173", "title": "Report of police officer on completion of investigation", "description": "Every investigation under this Chapter shall be completed without unnecessary delay and, as soon as it is completed, the officer in charge of the police station shall forward to a Magistrate empowered to take cognizance of the offence on a police report, a report in the form prescribed by the State Government.", "keywords": ["chargesheet", "police report", "completion of investigation", "cognizance"]},
        {"section": "CrPC 197", "title": "Prosecution of Judges and public servants", "description": "When any person who is or was a Judge or Magistrate or a public servant not removable from his office save by or with the sanction of the Government is accused of any offence alleged to have been committed by him while acting or purporting to act in the discharge of his official duty, no Court shall take cognizance of such offence except with the previous sanction of the Government.", "keywords": ["sanction to prosecute", "public servant", "government official", "prior sanction"]},
        {"section": "CrPC 313", "title": "Power to examine the accused", "description": "In every inquiry or trial, for the purpose of enabling the accused personally to explain any circumstances appearing in the evidence against him, the Court shall question him generally on the case.", "keywords": ["accused examination", "313 statement", "right to explain", "trial examination"]},
        {"section": "CrPC 437", "title": "When bail may be taken in case of non-bailable offence", "description": "When any person accused of, or suspected of, the commission of any non-bailable offence is arrested or detained without warrant by an officer in charge of a police station or appears or is brought before a Court, he may be released on bail.", "keywords": ["bail", "non-bailable offence", "bail conditions", "bail application"]},
        {"section": "CrPC 438", "title": "Direction for grant of bail to person apprehending arrest", "description": "When any person has reason to believe that he may be arrested on an accusation of having committed a non-bailable offence, he may apply to the High Court or the Court of Session for a direction under this section; and that Court may, if it thinks fit, direct that in the event of such arrest, he shall be released on bail.", "keywords": ["anticipatory bail", "pre-arrest bail", "Section 438", "anticipatory bail application"]},
        {"section": "CrPC 482", "title": "Saving of inherent powers of High Court", "description": "Nothing in this Code shall be deemed to limit or affect the inherent powers of the High Court to make such orders as may be necessary to give effect to any order under this Code, or to prevent abuse of the process of any Court or otherwise to secure the ends of justice.", "keywords": ["inherent powers", "High Court", "quashing FIR", "482 petition", "abuse of process"]},
    ]
    path = LEGAL_DB / "crpc_sections.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(crpc, f, indent=2, ensure_ascii=False)
    print(f"  [✓] crpc_sections.json — {len(crpc)} sections written")


def build_case_precedents():
    path = LEGAL_DB / "case_precedents.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(CASE_PRECEDENTS, f, indent=2, ensure_ascii=False)
    print(f"  [✓] case_precedents.json — {len(CASE_PRECEDENTS)} precedents written")


def build_sc_judgments():
    path = LEGAL_DB / "supreme_court_judgments.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(SUPREME_COURT_JUDGMENTS, f, indent=2, ensure_ascii=False)
    print(f"  [✓] supreme_court_judgments.json — {len(SUPREME_COURT_JUDGMENTS)} judgments written")


def build_high_court_judgments():
    hc_judgments = [
        {"case_name": "Naz Foundation v. Govt of NCT Delhi", "citation": "(2009) 160 DLT 277", "court": "Delhi High Court", "year": 2009, "area": "Criminal — Section 377", "held": "Section 377 IPC read down to exclude consensual same-sex adult acts.", "keywords": ["Section 377", "LGBT", "decriminalization", "Delhi HC"]},
        {"case_name": "Arnab Goswami v. State of Maharashtra", "citation": "2020 SCC Online SC 964", "court": "Supreme Court of India", "year": 2020, "area": "Criminal — Bail in Media Case", "held": "Bail granted to journalist. Personal liberty under Article 21 cannot be sacrificed to satisfy popular sentiment.", "keywords": ["bail", "Article 21", "personal liberty", "media", "journalism"]},
        {"case_name": "Nupur Sharma v. Ashwini Kumar Upadhyay", "citation": "(2019) SCC Online Del 8986", "court": "Delhi High Court", "year": 2019, "area": "Constitutional — Uniform Civil Code", "held": "Directions to Union to file response on petition seeking UCC. Court noted the Constitutional mandate under Article 44.", "keywords": ["uniform civil code", "UCC", "Article 44", "personal law reform"]},
    ]
    path = LEGAL_DB / "high_court_judgments.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(hc_judgments, f, indent=2, ensure_ascii=False)
    print(f"  [✓] high_court_judgments.json — {len(hc_judgments)} judgments written")


def main():
    LEGAL_DB.mkdir(parents=True, exist_ok=True)
    print("\n" + "=" * 60)
    print("  LexAI — Legal Database Builder")
    print("=" * 60)

    build_ipc_sections()
    build_crpc_sections()
    build_case_precedents()
    build_sc_judgments()
    build_high_court_judgments()

    print("\n" + "=" * 60)
    print("  Legal database built successfully!")
    print(f"  Location: {LEGAL_DB}")
    print("=" * 60 + "\n")


if __name__ == "__main__":
    main()
